### PR TITLE
Correct flag help text for -sequential-warmup, show number of fd and thread # on failure

### PR DESCRIPTION
**Pull request by ldemailly**
So for instance on mac one gets:
```
$ go run . load -t 10s -qps 10000 -c 16383 -uniform -sequential-warmup http://localhost:8080 
12:13:55.544 r1 [INF] scli.go:125> Starting, command="Φορτίο", version="dev  go1.22.3 arm64 darwin", go-max-procs=11
Fortio dev running at 10000 queries per second, 11->11 procs, for 10s: http://localhost:8080
12:13:55.544 r1 [INF] httprunner.go:121> Starting http test, run=0, url="http://localhost:8080", threads=16383, qps="10000.0", warmup="sequential", conn-reuse=""
12:13:59.317 r1 [ERR] http_client.go:951> Unable to connect, dest={"IP":"127.0.0.1","Port":8080,"Zone":""}, err="dial tcp 127.0.0.1:8080: connect: can't assign requested address", numfd=16312, thread=16303, run=0
Aborting because of error -1 for http://localhost:8080 (0 body bytes), thread# 16303
exit status 1
```

### CODE REVIEW

**Review by wiardvanrij — APPROVED** [review]

**Comment by ldemailly** [comment]
Thank Wiard!

of note, on Mac the ephemeral range allows for only 16k socket per address, so to get 30k for instance, one can use both ipv4 and ipv6 using:

```
fortio load -resolve-ip-type ip -t 10s -qps 60000 -c 30000 -uniform -sequential-warmup http://localhost:8080/ 
[...]
Sockets used: 30000 (for perfect keepalive, would be 30000)
IP addresses distribution:
[::1]:8080: 15000
127.0.0.1:8080: 15000
All done 600000 calls (plus 30000 warmup) 4.211 ms avg, 57080.5 qps
```

Note that  `-sequential-warmup` is needed or the client overwhelms the accept queue of the server, likewise one gets timeout if using max qps

**Comment by ldemailly** [comment]
Looks like https://expired.badssl.com/ is having a bad time, making the tests fail

**Comment by ldemailly** [comment]
on the other hand using ifconfig aliases doesn't seem to help getting past 16k somehow

testing using
```
$ host ltest.fortio.org
ltest.fortio.org has address 127.0.0.1
ltest.fortio.org has address 127.0.0.2
ltest.fortio.org has address 127.0.0.3
```
(which is used for the dns tests)

when it works, eg -c 15000:
```
Sockets used: 15000 (for perfect keepalive, would be 15000)
IP addresses distribution:
127.0.0.3:8080: 5000
127.0.0.1:8080: 5000
127.0.0.2:8080: 5000
Code 200 : 300000 (100.0 %)
```
but with 20k (`go run . load  -t 10s -qps 40000 -c 20000 -uniform -sequential-warmup http://ltest.fortio.org:8080`) connections it doesn't:
```
15:27:07.668 r1 [ERR] http_client.go:951> Unable to connect, dest={"IP":"127.0.0.3","Port":8080,"Zone":""}, err="dial tcp 127.0.0.3:8080: connect: can't assign requested address", numfd=16236, thread=16226, run=0
```

that's after doing:
```
sudo ifconfig lo0 alias 127.0.0.2 up
sudo ifconfig lo0 alias 127.0.0.3 up
```
on the mac

**Comment by ldemailly** [comment]
Of note that it works out of the box, without aliases on Ubuntu - only mac seems impossible to get more than ephemeral range even using multiple IPs / processes

https://gophers.slack.com/archives/C0VP8EF3R/p1717176825516469?thread_ts=1717126658.917799&cid=C0VP8EF3R

**Comment by ldemailly** [comment]
See #928 for the suddenly appearing yet unrelated to changes here, data race

**Pull request merged**
