### PR TITLE
fix 100% error and undefined in UI

### LINKED ISSUE #168: fortio UI for grpc results is misleading/incomplete
Follow up from #152 

- results are missing
- shows "100% error" all the time
- shows undefined as the url

screen shot 2018-02-28 at 9 56 28 pm

### PR DESCRIPTION
**Pull request by asadali**
fixes #168 

fix-168

bit ugly with if/else checks. will welcome feedback for improvement

### CODE REVIEW

**Comment by ldemailly** [comment]
thanks, I think we should have at least 1 explicit "Type" in the json to identify the load test type
but that can be a different cleanup I suppose

**Review by ldemailly — APPROVED** [review]
incrementally better, ty

**Comment by asadali** [comment]
is it ok to merge this with the failed codecov check?

also, about the first PR build circle/ci failure:

```
gometalinter --concurrency=2 \
--deadline=180s --enable-all --aggregate \
--exclude=.pb.go --disable=gocyclo --line-length=132 . ./fhttp ./version ./stats ./fnet ./fgrpc ./periodic ./echosrv ./histogram ./ui ./log
WARNING: failed to make httprunner_test.go a relative path: lstat httprunner_test.go: no such file or directory
httprunner_test.go:78::error: Number go routine before test 37 (test)
Makefile:36: recipe for target 'local-lint' failed
```
not sure why an error was raised during linting, any thoughts on it?

**Comment by ldemailly** [comment]
#178 for ⭕️

**Pull request merged**
