### PR TITLE
remove logic to escape % in given urls

### LINKED ISSUE #181: % escaping makes loading URLs through fetch not work
http://X/fortio/fetch/Y/fortio1/fortio/?labels=Fortio&url=localhost%3A8080/echo&qps=100&t=3s&n=&c=8&p=50%2C+75%2C+90%2C+99%2C+99.9&r=0.0001&H=User-Agent%3A+istio%2Ffortio-0.8.0-pre&H=&H=&runner=http&save=on&load=Start

->

Fortio localhost%3A8080/echo

Aborting because unable to create client 0 for http://localhost%253A8080/echo

going to debug shows the issue:

GET /debug?labels=Fortio&url=localhost%253A8080/echo&qps=100&t=3s&n=&c=8&p=50%252C+75%252C+90%252C+99%252C+99.9&r=0.0001&H=User-Agent%253A+istio%252Ffortio-0.8.0-pre&H=&H=&runner=http&save=on&load=Start HTTP/1.1

%253A instead of %3A

### PR DESCRIPTION
**Pull request by asadali**
fixes #181 

@ldemailly this is a minor fix that I had on my local version as the escape logic failed a few of my perf test URLs. sending this in based on discussion on 181.

did i miss any documentation updates?

### CODE REVIEW

**Comment by ldemailly** [comment]
you need to change the default value on the UI I think - a test should fail (or maybe I don't have a test that simulates clicking the start button)

also probably add a test more explictly that a url with a %3F doesn't get mangled

**Comment by asadali** [comment]
gotcha. was working on the tests. thanks for the clarifications

**Comment by ldemailly** [comment]
basically, try

fortio server &
visit http://[::1]:8080/ and click start, it will probably fail to do the % with this PR

I'm still wondering if I could preserve the feature somehow but I guess it's rather low pri

**Comment by ldemailly** [comment]
need UI test somehow as it's not caught (long term/future)

**Comment by asadali** [comment]
surprisingly, i don't see an error for the default UI run with the % in the query. even with the changes in this PR

ui-remove-escape

**Comment by ldemailly** [comment]
that's the point - you get "no error" while the sample url for instance asks for 0.5% of 503 and 1.5% of 429

ditto for the delay not showing up

**Comment by ldemailly** [comment]
there should be some error in the server log too about not able to parse delay and status

**Comment by ldemailly** [comment]
let's try to finish this for 0.8.0 which I want to do soon

**Comment by asadali** [comment]
thanks for the insights. I hadn't fully understood the significance of escaping the url.

now, based on how http_utils -> generateStatus and generateDelay are programmed, they should work equally well without a % suffix. I am guessing the % was for aesthetic/intuitive reasons. (i am not making a change to removePercent)

also, removed % from the default URL on the UI and the parameters are being parsed correctly for configuring echo server's behavior

I didn't add an extra Test but modified MultiIinitAndEscape to test for the %3A case

**Comment by asadali** [comment]
will you prefer that i add a test for the url mentioned in the issue.

something like 
```
# Check we can connect, and run a http QPS test against ourselves through fetch with an escaped URL
$CURL "${BASE_FORTIO}fetch/localhost:8080$FORTIO_UI_PREFIX?url=localhost%3A8080/echo&qps=100&t=3s&n=&c=8&p=50%2C+75%2C+90%2C+99%2C+99.9&json=on&load=Start" | grep ActualQPS
```

or should i edit the basic QPS test to match the URL being displayed in the UI

**Review by ldemailly — APPROVED** [review]
it's ok I think just harder to guess what :x does

**Pull request merged**
