### PR TITLE
improve syntax in code and comments by using jargonLint

### PR DESCRIPTION
**Pull request by ccoVeille**
- **chore: fix acronyms, typos and style**
- **chore: fix acronym in fortio --help**

I used my own project to spot the changes

https://github.com/jargonLint/jargonLint

Replace 

- #942
- #943

### CODE REVIEW

**Comment by ldemailly** [comment]
Merci! repeating here

is the README change from
```
release/bumpRelease.sh 1.65.0 -f
```
(it should)

**Comment by ldemailly** [comment]
Thanks! Awesome ! can you link your tool in the description of this MR so there is a trace

**Review by ldemailly — APPROVED** [review]
Thanks! Awesome ! can you link your tool in the description of this MR so there is a trace

**Comment by ccoVeille** [comment]
https://github.com/jargonLint/jargonLint

**Comment by ccoVeille** [comment]
Feel free to merge whenever you want.

Even if you somehow gave me the right to do it, I would prefer let you do it.

**Pull request merged**
