### PR TITLE
Switch header change logging to verbose

### LINKED ISSUE #117: change fetch log or run with -loglevel warning in perf setup
when running a fetch load test the log is floody:
```
06:35:06 I uihandler.go:426> Fetch: GET /fortio/fetch/echosrv1:8080/echo HTTP/1.1 127.0.0.1:54818 (http)
06:35:06 I http.go:167> Setting regular extra header X-On-Behalf-Of: 127.0.0.1:54818
```

### PR DESCRIPTION
**Pull request by ldemailly**
Fixes #117

### CODE REVIEW

**Comment by ldemailly** [comment]
going to keep the Fetch log as it's an accesslog of sort but the extra header is just noise

**Review by danehans — COMMENTED** [review]
Can you help me understand why L167 is set to `log.LogVf` but `if strings.EqualFold(key, "host")` is set to `log.Infof`?

**Comment by ldemailly** [comment]
because the Host header is quite special / not to be missed but maybe I should change it too

**Comment by ldemailly** [comment]
@danehans changed, ptal

**Review by danehans — APPROVED** [review]
lgtm

**Pull request merged**
