### PR TITLE
close #283 - add + button to add more custom headers

### LINKED ISSUE #283: fortio UI: add + button to add more custom headers
fortio UI: add + button to add more custom headers

### PR DESCRIPTION
**Pull request by SeriyBg**
closes #283 - add + button to add more custom headers

### CODE REVIEW

**Review by ldemailly — COMMENTED** [review]
Thanks for this, but is a new file for 1 function really best/useful? why not putting it either inline in the template or inside the existing js

**Comment by SeriyBg** [comment]
@ldemailly thanks for your comment. Have moved this function existing js file. I just thought that fortio_chart.js does not represent the functionality of the main page but rather represent the chart page

**Comment by ldemailly** [comment]
it could be "fortio.js" I guess, though at some point it can be more OO (there is a TODO somewhere I believe)

can I ask you a 1 time favor, the google cla bot isn't working here (yet), so can you make a dummy PR in istio/istio so I can see you signed the CLA

for instance you can edit 
https://github.com/istio/istio/blob/master/tools/README.md

add some space and submit a PR, later abandon it once CLA bot has commented, and link this PR

Thanks!

**Review by ldemailly — APPROVED** [review]
You tested it right :-) ? (added say 5 headers)

**Comment by SeriyBg** [comment]
@ldemailly Yes, of course, I have tested it :)
Created a dummy PR and referenced this one there. It's labeled `cla:yes`, so I have closed that PR already but it's linked to this one

**Comment by ldemailly** [comment]
Thanks for your contribution!

**Pull request merged**
